name: Build & Test

on: pull_request

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest

    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile --non-interactive --ignore-engines
      - run: yarn run test

  check-build-types:
    name: Check build types are valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --non-interactive --ignore-engines
      - run: yarn ts:bundle-types-from-redocly
      - run: yarn test:check-build-types
