name: Build & Test

on: pull_request

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14']

    name: Run tests using node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn run test
      - run: yarn run ts:bundle-types-from-redocly
