name: Updates SDK resources based on api-definitions

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout api-definitions repo
        uses: actions/checkout@v2
        with:
          repository: 'Rebilly/api-definitions'
          path: 'api-definitions'
          # Here we need to use the name of the branch that triggered this workflow  
          ref: 'add-sdk-names-to-operations'
      - name: Builds openAPI json schemas
        working-directory: 'api-definitions'
        run: |
          npm install
          npx openapi bundle -o dist --ext json
      - name: Checkout rebilly-js-sdk repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout sdk generator repo
        uses: actions/checkout@v2
        with:
          repository: 'Rebilly/rebilly-sdk-generator'
          path: 'rebilly-sdk-generator'
          # This will end up being master once we merge the last version of the generator 
          ref: 'add-local-generation'
          token: ${{ secrets.SDK_GENERATOR_PAT }}
      - name: Executes sdk generation
        working-directory: ./rebilly-sdk-generator
        run: |
          npm install
          echo 'LS:'
          ls
          ls ../api-definitions/dist
          npm run generate-sdk-code --local
          echo 'listing root dir'
          ls ../../
          echo 'listing GITHUB_WORKSPACE'
          ls ${{ env.GITHUB_WORKSPACE }}
      - name: Set new branch name
        run: echo ::set-output name=branch-name::"test"
      - name: Debug step
        run: |
          echo 'listing GITHUB_WORKSPACE'
          ls ${{ env.GITHUB_WORKSPACE }}
          cd src/resources
          touch test.txt
      # - name: Create PR
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.SDK_GENERATOR_PAT }}
      #     title: 'First automated sample PR'
      #     draft: true
      #     branch: 'auto-pr'
      #     base: 'master'
      - name: Update api definitions PR
        run: |
          gh pr list
          gh pr status --repo rebilly/rebilly-js-sdk
        env:
          GITHUB_TOKEN: ${{ secrets.SDK_GENERATOR_PAT }}
